sludio_helper_redis:
    path: /redis
    defaults:
        _controller: Sludio\HelperBundle\Script\Controller\ScriptController::redisAction
    options:
        i18n: false
        
sludio_helper_cache:
    path: /cache
    defaults:
        _controller: Sludio\HelperBundle\Script\Controller\ScriptController::cacheAction
    options:
        i18n: false
        
sludio_helper_generate:
    path: /generate
    defaults:
        _controller: Sludio\HelperBundle\Translatable\Controller\TranslatableController::generateAction
    options:
        i18n: false

sludio_helper_ibrows:
    path: /ibrows
    defaults:
        _controller: Sludio\HelperBundle\Script\Controller\ScriptController::ibrowsAction
    options:
        i18n: false
