sludio_helper_redis:
    path: /redis
    defaults:
        _controller: SludioHelperBundle:Scripts:redis
    options:
        i18n: false
        
sludio_helper_cache:
    path: /cache
    defaults:
        _controller: SludioHelperBundle:Scripts:cache
    options:
        i18n: false
        
