sludio_helper_redis:
    path: /redis
    defaults:
        _controller: Sludio\HelperBundle\Script\Controller\ScriptController::redisAction
    options:
        i18n: false

sludio_helper_cache:
    path: /cache
    defaults:
        _controller: Sludio\HelperBundle\Script\Controller\ScriptController::cacheAction
    options:
        i18n: false

sludio_helper_generate:
    path: /generate
    defaults:
        _controller: Sludio\HelperBundle\Script\Controller\ScriptController::generateAction
    options:
        i18n: false

sludio_helper_lexik:
    path: /lexik
    defaults:
        _controller: Sludio\HelperBundle\Script\Controller\ScriptController::lexikAction
    options:
        i18n: false

sludio_helper_position:
    resource: "@SludioHelperBundle/Position/Resources/config/routing.yml"
    options:
        i18n: false