sludio_helper_redis:
    path: /redis
    defaults:
        _controller: Sludio\HelperBundle\Scripts\Controller\ScriptController::redisAction
    options:
        i18n: false
        
sludio_helper_cache:
    path: /cache
    defaults:
        _controller: Sludio\HelperBundle\Scripts\Controller\ScriptController::cacheAction
    options:
        i18n: false
        
