sludio_helper_redis:
    path: /redis
    defaults:
        _controller: Sludio\HelperBundle\Script\Controller\ScriptController::redisAction
    options:
        i18n: false

sludio_helper_cache:
    path: /cache
    defaults:
        _controller: Sludio\HelperBundle\Script\Controller\ScriptController::cacheAction
    options:
        i18n: false

sludio_helper_generate:
    path: /generate
    defaults:
        _controller: Sludio\HelperBundle\Script\Controller\ScriptController::generateAction
    options:
        i18n: false

sludio_helper_lexik:
    path: /lexik
    defaults:
        _controller: Sludio\HelperBundle\Script\Controller\ScriptController::lexikAction
    options:
        i18n: false

sludio_helper_movedown:
    path: /movedown/{class}/{id}
    defaults:
        _controller: Sludio\HelperBundle\Position\Controller\TreeController::moveAction
        position: 'down'
    options:
        i18n: false

sludio_helper_moveup:
    path: /moveup/{class}/{id}
    defaults:
        _controller: Sludio\HelperBundle\Position\Controller\TreeController::moveAction
        position: 'up'
    options:
        i18n: false

sludio_sitemap_generate:
    path: /sitemap
    defaults:
        _controller: Sludio\HelperBundle\Script\Controller\ScriptController::sitemapGenerateAction
    options:
        i18n: false

sludio_sitemap:
    path: /sitemap.xml
    defaults:
        _controller: Sludio\HelperBundle\Script\Controller\ScriptController::sitemapAction
    options:
        i18n: false

sludio_helper_display_alerts:
    path: /display_alerts
    defaults:
        _controller: Sludio\HelperBundle\Script\Controller\FlashController::displayAlertsAction
