services:
    sludio_helper.logger:
        class: "%sludio_helper.logger.class%"
        lazy: true
        arguments:
            - "@logger"
        tags:
            -
                name: monolog.logger
                channel: sludio_helper
