parameters:
    lexik_translation.translator.class: Sludio\HelperBundle\Translatable\Component\Translation\Translator
    jms_i18n_routing.locale_resolver.class: Sludio\HelperBundle\Translatable\Router\DefaultLocaleResolver

imports:
    -
        resource: '../../Translatable/Resources/config/services.yml'
    -
        resource: '../../Missing/Resources/config/services.yml'
    -
        resource: '../../Beautify/Resources/config/services.yml'
    -
        resource: '../../Position/Resources/config/services.yml'
    -
        resource: '../../Browser/Resources/config/services.yml'

services:
    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            -
                name: doctrine.event_subscriber
                connection: default
        calls:
            -
                - setAnnotationReader
                -
                    - "@annotation_reader"
