language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache/files

matrix:
    include:
        - php: 7.0
        - php: 7.1
        
before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install
