services:
    sludio_helper.command.client_create:
        class: Sludio\HelperBundle\Oauth\Command\CreateClientCommand
        tags:
            -
                name: console.command

    sludio_helper.oauth2.provider_factory:
        class: Sludio\HelperBundle\DependencyInjection\ProviderFactory
        public: false
        arguments:
            - "@router"

    sludio_helper.oauth2.registry:
        class: Sludio\HelperBundle\Oauth\Client\ClientRegistry
        arguments:
            - "@service_container"
            - ~
            
    oauth2.registry:
        alias: sludio_helper.oauth2.registry

    sludio_helper.oauth2.base_service:
        class: Sludio\HelperBundle\Oauth\Service\BaseService
        arguments:
            - "%sludio_helper.oauth.clients%"
            
        tags:
            - 
                name: monolog.logger
                channel: oauth2_service
