services:
    sludio_helper.command.client_create:
        class: Sludio\HelperBundle\Oauth\Command\CreateClientCommand
        tags:
            -
                name: console.command

    sludio_helper.command.token_clear:
        class: Sludio\HelperBundle\Oauth\Command\ClearOldTokensCommand
        tags:
            -
                name: console.command

    sludio_helper.oauth.provider_factory:
        class: Sludio\HelperBundle\DependencyInjection\ProviderFactory
        public: false
        arguments:
            - "@router"
            - "@request_stack"

    sludio_helper.oauth.registry:
        class: Sludio\HelperBundle\Oauth\Utils\ClientRegistry
        arguments:
            - "@service_container"
            - ~

    oauth.registry:
        alias: sludio_helper.oauth.registry

    sludio_helper.registry:
        class: Sludio\HelperBundle\Oauth\Utils\ClientOpenIDRegistry
        arguments:
            - "@service_container"
            - ~
            - ~

    openauth.registry:
        alias: sludio_helper.registry
