services:
    sludio_helper.command.client_create:
        class: Sludio\HelperBundle\Oauth\Command\CreateClientCommand
        tags:
            -
                name: console.command

    sludio_helper.oauth.provider_factory:
        class: Sludio\HelperBundle\DependencyInjection\ProviderFactory
        public: false
        arguments:
            - "@router"

    sludio_helper.oauth.registry:
        class: Sludio\HelperBundle\Oauth\Client\ClientRegistry
        arguments:
            - "@service_container"
            - ~
            
    oauth.registry:
        alias: sludio_helper.oauth.registry

    sludio_helper.oauth.call_service:
        class: Sludio\HelperBundle\Oauth\Service\CallService
        arguments:
            - "%sludio_helper.oauth.clients%"
            - "@session"
            # - "@doctrine.orm.unicorn_entity_manager"
        tags:
            - 
                name: monolog.logger
                channel: oauth_service

    # sludio_helper.oauth.oracle_service:
        
