services:
    sludio_helper.form.type.translator:
        class:     Sludio\HelperBundle\Translatable\Form\Type\TranslatorType
        arguments:  
            - '%sludio_helper.translatable.locales%'
            - '@sludio_helper.translatable.manager'
            - '@translator'
        tags:
            -  
                name: form.type
                alias: translations

    sludio_helper.translatable.manager:
        class: Sludio\HelperBundle\Translatable\Helper\Manager
        arguments: 
            - "@doctrine"

    sludio_helper.twig.translate_extension:
        class: Sludio\HelperBundle\Translatable\Twig\TranslationExtension
        public: false
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@request_stack'
            - '%locale%'
        tags:
            - 
                name: twig.extension

    sludio_helper.command.generate_translations:
        class: Sludio\HelperBundle\Translatable\Command\TranslationsGenerateCommand
        tags:
            -
                name: console.command
