services:
    sludio_helper.command.redis_flush:
        class: Sludio\HelperBundle\Script\Command\RedisFlushCommand
        public: true
        tags:
            -
                name: console.command

    sludio_helper.twig.extension:
        class: Sludio\HelperBundle\Script\Twig\SludioExtension
        public: false
        arguments:
            - '%sludio_helper.script.short_functions%'
            - "%kernel.root_dir%"
            - "@request_stack"
        tags:
            -
                name: twig.extension

    sludio_helper.twig.missing_extension:
        class: Sludio\HelperBundle\Script\Twig\MissingExtension
        public: false
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '%sludio_helper.script.short_functions%'
        tags:
            -
                name: twig.extension

    sludio_helper.repository.insert:
        class: Sludio\HelperBundle\Script\Repository\InsertRepository
        public: true
        arguments:
            - '@doctrine'
            - '%sludio_helper.entity.manager%'

    sludio_helper.service.mobile_detect:
        class: Mobile_Detect
