services:
    sludio_helper.command.redis_flush:
        class: Sludio\HelperBundle\Script\Command\RedisFlushCommand
        tags:
            -
                name: console.command

    sludio_helper.twig.beautify_extension:
        class: Sludio\HelperBundle\Script\Twig\BeautifyExtension
        public: false
        arguments:
            - '@request_stack'
            - '@doctrine.orm.default_entity_manager'
            - '@service_container'
        tags:
            -
                name: twig.extension

    sludio_helper.twig.browser_extension:
        class: Sludio\HelperBundle\Script\Twig\BrowserExtension
        public: false
        arguments:
            - '@service_container'
        tags:
            -
                name: twig.extension

    sludio_helper.twig.gulp_extension:
        class: Sludio\HelperBundle\Script\Twig\GulpExtension
        public: false
        arguments:
            - "%kernel.root_dir%"
            - "@kernel"
            - '@service_container'
        tags:
            -
                name: twig.extension

    sludio_helper.twig.missing_extension:
        class: Sludio\HelperBundle\Script\Twig\MissingExtension
        public: false
        arguments:
            - '@request_stack'
            - '@doctrine.orm.default_entity_manager'
            - '@service_container'
        tags:
            -
                name: twig.extension

    sludio_helper.twig.usort_extension:
        class: Sludio\HelperBundle\Script\Twig\UsortExtension
        public: false
        arguments:
            - '@service_container'
        tags:
            -
                name: twig.extension
