sludio_helper_movedown:
    path: /movedown/{class}/{id}
    defaults:
        _controller: Sludio\HelperBundle\Position\Controller\TreeController::moveAction
        position: 'down'

sludio_helper_moveup:
    path: /moveup/{class}/{id}
    defaults:
        _controller: Sludio\HelperBundle\Position\Controller\TreeController::moveAction
        position: 'up'

