sludio_helper_movedown:
    pattern: /movedown/{class}/{id}
    defaults:
        _controller: Sludio\HelperBundle\Position\Controller\TreeController::downAction

sludio_helper_moveup:
    pattern: /moveup/{class}/{id}
    defaults:
        _controller: Sludio\HelperBundle\Position\Controller\TreeController::upAction