services:
    sludio_helper.position.orm:
        class: Sludio\HelperBundle\Position\Service\PositionHandler
        public: false
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        calls:
            -
                - setPositionField
                -
                    - "%sludio_helper.position.position.field%"
    
    sludio_helper.twig.extension:
        class: Sludio\HelperBundle\Position\Twig\ObjectPositionExtension
        arguments:
            - "@sludio_helper.position"
        public: false
        tags:
            - 
                name: twig.extension
