services:
    sludio_helper.position_handler:
        class: Sludio\HelperBundle\Position\Service\PositionHandler
        public: false
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        calls:
            -
                - setPositionField
                -
                    - "%sludio_helper.position.field%"

    sludio_helper.twig.position_extension:
        class: Sludio\HelperBundle\Position\Twig\ObjectPositionExtension
        arguments:
            - "@sludio_helper.position_handler"
            - '%sludio_helper.script.short_functions%'
        public: false
        tags:
            -
                name: twig.extension

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            -
                name: doctrine.event_subscriber
                connection: default
        calls:
            -
                - setAnnotationReader
                -
                    - "@annotation_reader"
