services:
    sludio_helper.openidconnect.registry:
        class: Sludio\HelperBundle\Openidconnect\Utils\ClientRegistry
        arguments:
            - "@service_container"
            - ~

    openidconnect.registry:
        alias: sludio_helper.openidconnect.registry
