services:
    sludio_helper.openidconnect.registry:
        class: Sludio\HelperBundle\Script\Utils\ClientRegistry
        public: true
        arguments:
            - ~
        calls:
            -
                - setContainer
                -
                    - "@service_container"

    openidconnect.registry:
        alias: sludio_helper.openidconnect.registry
        public: true
