services:
    sludio_helper.twig.pagination_extension:
        class: Sludio\HelperBundle\Pagination\Twig\PaginationExtension
        public: false
        arguments:
            - '@service_container'
            - '%sludio_helper.script.short_functions%'
        tags:
            -
                name: twig.extension
