services:
    sludio_helper.guzzle.data_collector.history_bag:
        class: Sludio\HelperBundle\Guzzle\GuzzleHttp\History\History

    sludio_helper.guzzle.data_collector.guzzle:
        class: Sludio\HelperBundle\Guzzle\DataCollector\GuzzleCollector
        arguments:
            - ~
            - "@sludio_helper.guzzle.data_collector.history_bag"
        tags:
            -
                name: data_collector
                template: "@SludioHelper/Guzzle/Collector/guzzle.html.twig"
                id: guzzle

    sludio_helper.guzzle.middleware.stopwatch:
        class: Sludio\HelperBundle\Guzzle\GuzzleHttp\Middleware\StopwatchMiddleware
        arguments:
            - "@debug.stopwatch"
        tags:
            -
                name: sludio_helper.guzzle.middleware
                alias: stopwatch

    sludio_helper.guzzle.middleware.history:
        class: Sludio\HelperBundle\Guzzle\GuzzleHttp\Middleware\HistoryMiddleware
        arguments:
            - "@sludio_helper.guzzle.data_collector.history_bag"
        tags:
            -
                name: sludio_helper.guzzle.middleware
                alias: history
                priority: -1000

    sludio_helper.guzzle.middleware.logger:
        class: Closure
        arguments:
            - "@logger"
            - "@sludio_helper.guzzle.logger.message_formatter"
            - ~
        factory:
            - GuzzleHttp\Middleware
            - log
        tags:
            -
                name: sludio_helper.guzzle.middleware
                alias: logger

    sludio_helper.guzzle.logger.message_formatter:
        class: GuzzleHttp\MessageFormatter
        public: false
        arguments:
            - ~

    sludio_helper.guzzle.middleware.cache:
        class: Sludio\HelperBundle\Guzzle\GuzzleHttp\Middleware\CacheMiddleware
        arguments:
            - "@sludio_helper.guzzle.cache_adapter"
        tags:
            -
                name: sludio_helper.guzzle.middleware
                alias: cache
                priority: -1500