services:
    sludio_browser.twig.browser_extension:
        class: Sludio\HelperBundle\Browser\Twig\BrowserExtension
        public: false
        tags:
            - 
                name: twig.extension
